### PR TITLE
Improve CAH Creator integration

### PR DESCRIPTION
**Pull request by tjhorner**
CAH Creator 2.0 is out, and I want to improve some stuff here too! The biggest change is that now there's a picker window instead of having to manually type the deck ID in:

image

There was also a bump of the `cah-creator` module to 1.0.2 which fixed a big error that caused successful requests to throw errors.

### CODE REVIEW

**Comment by Rylius** [comment]
I kinda doubt this'll work: https://github.com/Rylius/CardsAgainstEquestria/pull/144/files#diff-ed37b4344c2a10d05c42df85104d69b2R155
Window size also seems to be a little large.

Might need a couple days to take a closer look and merge though

Nice work on the site!

**Comment by tjhorner** [comment]
Haha, nice catch. Forgot to change that. And the window size is large for now since I haven't really optimized the page layout yet, but it works for now. I'll change that hostname right now.

**Comment by tjhorner** [comment]
ETA on merge into master then production? CAH Creator integration is completely broken right now (it's probably CloudFlare's fault...)

**Comment by Rylius** [comment]
I wanted to take a closer look at exactly these cases where CAH Creator is down to make sure CAE doesn't crash entirely (which it may or may not be doing right now).

Probably going to update later tonight.

**Comment by tjhorner** [comment]
> I wanted to take a closer look at exactly these cases where CAH Creator is down

It's not necessarily "down", it's just not accessible because the library I used for `cah-creator` doesn't follow redirects, thus just returning CloudFlare's redirect HTML, making it impossible to parse.

Anyway, I devised a temporary fix while you test (I just disabled the HTTPS redirects lol).

**Comment by Rylius** [comment]
Well but there might be cases where it's day, and I want to make sure it's not affecting CAE. :)

**Comment by tjhorner** [comment]
Of course, Node.js is prone to crashing from the smallest exceptions, heh.

The fix seems to work for now:

image

**Comment by Rylius** [comment]
https://github.com/Rylius/CardsAgainstEquestria/commit/fd276901501266cae019f6a9937b8779a1f7c21b

**Comment by Rylius** [comment]
https://github.com/Rylius/CardsAgainstEquestria/releases/tag/1.0.10

Updating in a few minutes once people finish their games

**Comment by Rylius** [comment]
Update deployed and seems to be working. :)

**Comment by tjhorner** [comment]
Hooray! Awesome, I'll see what I can do to make that window size smaller and look nicer.

**Comment by Rylius** [comment]
I've decreased it a little already, should be okay for most people anyway

**Comment by tjhorner** [comment]
Yeah I noticed, I mean so it looks more like a vertical list instead of a grid. And uh, there's no padding on the border (but that's my fault):

image

**Pull request merged**
