### PR TITLE
Add custom sets, fix a few bugs

### PR DESCRIPTION
**Pull request by tjhorner**
This pull request adds integration with [cahcreator.com](http://cahcreator.com), a lightweight, collaborative Cards Against Humanity deck creator. Game hosts will be able to add custom decks to their games via the deck ID on CAH Creator; they will not be permanently stored on the server. However, decks must have at least 3 black cards and 5 white cards. They do count as expansions, so users will still need to pick a main deck.

I don't really know Knockout.js that well, so if you find anything that could be improved with it, please tell me! I added some TODOs where I believe that the code could be improved or a feature could be added.

I'm probably going to be adding raw JSON import if you don't merge this right away -- so if you want to use that instead of some shady third-party service, then hold off from merging it until then. :wink: ([CAH Creator is actually open-source...](/tjhorner/cah-creator))

Oh, and don't mind the whitespace removal on the migrations, it should't affect them. Atom likes saving bytes.

## Things that need to be fixed or added
- Auto adding sets (as in, a button on CAH Creator to add to your current game)
- Add the custom set to the expansions once it's added and disable the modal (right now, users get notified through chat that the host added a custom set)

(when I fixed the merge conflict, it apparently still had the commits from master. they don't seem to be a problem but I can close and re-open this again with them removed if you want, I was just too lazy and it's 11:30 PM here)

### CODE REVIEW

**Comment by Rylius** [comment]
Ultimately (version 2.0 or something) I'd like to abstract deck loading quite a bit more so we could register "deck providers" without having to touch the actual game class. This PR is fine for now, moving the changes later shouldn't be too much trouble. Just a FYI for what I have planned :)

What bothers me is the additional JSON route, I'd prefer to have the custom set stuff inside the general lobby updates.
Using the existing lobby updates it's also much easier to add the custom sets to the Knockout view model, so the set can be added to the existing expansions tab.
Should also make it easier to handle multiple custom sets instead of just one, as well as removing them again (which doesn't seem possible right now?).
That'd mean moving the CAH Creator API call into Game#update... not a good place, but this can be refactored into loading decks asynchronously as they are added later. I like that. :)

I can make those changes myself if that's cool with you.

Is there any specific reason why there need to be at least 3 white and 5 black cards? CAE doesn't really care about the number of cards in a deck; empty decks are perfectly fine (even if they make little sense).

**Comment by Rylius** [comment]
Great work on CAH Creator by they way, highly appreciate the work!
Lemme know if you need any additional API routes for tighter integration (automatically adding the deck to a game would be sweet as hell!).

**Comment by tjhorner** [comment]
>Is there any specific reason why there need to be at least 3 white and 5 black cards? CAE doesn't really care about the number of cards in a deck; empty decks are perfectly fine (even if they make little sense).

You just answered your own question haha, an empty deck would just make no sense. I can remove the check if you'd like.

**Comment by tjhorner** [comment]
>as well as removing them again (which doesn't seem possible right now?).

Well, it uh, almost is. You could refresh the page, make an empty deck on CAH Creator and then use that but no, there really isn't a way to remove `Game.customSet` after it's been assigned a set.

>Ultimately (version 2.0 or something) I'd like to abstract deck loading quite a bit more so we could register "deck providers" without having to touch the actual game class

That'd be pretty sweet!

>I can make those changes myself if that's cool with you.

Go for it, but that's the entire reason why I didn't put it in `/game/update ` heh

**Comment by Rylius** [comment]
Gonna be making the mentioned changes now-ish

**Comment by tjhorner** [comment]
Sounds good, approximately when will this be merged into master and deployed to prod?

**Comment by Rylius** [comment]
I have no idea!

If everything goes well in a couple hours, we'll see

**Comment by Rylius** [comment]
https://github.com/Rylius/CardsAgainstEquestria/commit/342f42819bd768f430549877ec6e1096324af792

Added support for multiple custom decks, added a list of currently selected custom decks (shown to all players in the lobby) and added ability to remove custom decks.
Wanna go live? :)

**Comment by tjhorner** [comment]
Yes. I'm late, it's already live!

**Pull request merged**
