### PR TITLE
Add Material theme

### PR DESCRIPTION
**Pull request by tjhorner**
This pull request adds a theme based off of Google's [material design](http://google.com/design/spec) using [Material Design for Bootstrap](https://github.com/FezVrasta/bootstrap-material-design). It has been tweaked to work with CAE and properly added in the license page.

Some of the pages have been tweaked to work with the material theme as well, I have tested the other themes while these pages were changed; they still work fine.

The material theme is also in `config.default.json` now, so you can copy that over!

Some screenshots!

index view

game list view

game play view

game create view 1

I personally love the way it makes modals look :)

game create view 2

Oh yeah, I also changed the modal up a bit to make the wording of "set" and "deck" consistent between the CAE and CAH Creator context.

### CODE REVIEW

**Comment by tjhorner** [comment]
Hold up, replacing the glyphs with material design icons.

**Comment by tjhorner** [comment]
Screenshot:

image

**Comment by Rylius** [comment]
I'd honestly prefer to not merge this since it adds a whole ton of bloat on top of Bootstrap (which is just bloat itself).
I don't think changing the design substantially before 2.0 makes much sense, all of the HTML has to be adjusted at some point as there is way too much coupling between HTML and Bootstrap.
For 2.0 I'd like to get rid of Bootstrap entirely.

**Comment by tjhorner** [comment]
That's fine, I'm just doing this for my local instance and thought I'd contribute back :smile:

**Pull request closed without merging**
